// This file is auto-generated by dotnet new xunit
// Delete or replace with actual tests

namespace Mcp.SqlApiServer.Tests;

public class UnitTest1
{
    [Fact]
    public void Test1()
    {
        Assert.True(true);
    }
}
